server:
  nodeSelector:
    type: addon

  tolerations:
  - key: type
    value: addon
    operator: "Equal"

  persistentVolume:
    enabled: false

alertmanager:
  enabled: false

kube-state-metrics:
  enabled: false

prometheus-node-exporter:
  enabled: false

prometheus-pushgateway:
  enabled: false
